// sections.js
export const sections = [
    {
        key: "inicio",
        title: "Inicio",
        fields: [
            "prioridad",
            "codigoImportacion",
            "proveedor",
            "facturaComercial",
            "ordenCompra",
            "regimen",
            "descripcion",
            "notificacionBroker",
            "referencia",
            "calloff",
            "fechaCalloff",
        ],
    },
    {
        key: "preembarque",
        title: "Pre-Embarque",
        fields: [
            "paisOrigen",
            "paisProcedencia",
            "fechaFactura",
            "valorFactura",
            "formaPago",
            "cantidad",
            "um",
            "entidadEmisoraDcp",
            "numeroPermisoImportacion",
            "fechaSolicitudRegimen",
            "cartaReg21",
            "fechaSolicitudGarantia",
            "aseguradora",
            "numeroGarantia",
            "montoAsegurado",
            "fechaInicioGarantia",
            "fechaFinGarantia",
            "numeroCdaGarantia",
            "fechaEnvioPoliza",
            "fechaRecepcionDocumentoOriginal",
            "numeroPoliza",
            "incoterms",
            "fechaRecolectEstimada",
            "fechaRecolectProveedor",
            "fechaRecolectReal",
            "fechaReqBodega",
            "fechaMaxReqBodega",
            "cartaAclaratoria",
            "certificadoOrigen",
            "listaEmpaque",
            "cartaGastos",

        ],
    },
    {
        key: "postembarque",
        title: "Post-Embarque",
        fields: [
            "blMaster",
            "blHijo",
            "tipoTransporte",
            "companiaTransporte",
            "forwarder",
            "fechaEstEmbarque",
            "fechaRealEmbarque",
            "fechaEstLlegadaPuerto",
            "fechaRealLlegadaPuerto",
            "numeroGuia",
            "fechaRecepcionDocsOriginales",
            "puertoEmbarque",
        ],
    },
    {
        key: "aduana",
        title: "Aduana",
        fields: [
            "fechaEnvioElectronico",
            "fechaPagoLiquidacion",
            "fechaSalidaAutorizada",
            "tipoAforo",
            "refrendo",
            "numeroEntregaEcuapass",
            "numeroLiquidacion",
            "numeroCdaAutorizacion",
            "numeroCarga",
            "statusAduana",
        ],
    },
    {
        key: "despacho",
        title: "Despacho",
        fields: [
            "fechaFacturacionCostos",
            "numeroContainer",
            "peso",
            "bultos",
            "tipoContenedor",
            "cantidadContenedores",
            "fechaEstDespachoPuerto",
            "fechaRealDespachoPuerto",
            "fechaEstEntregaBodega",
            "fechaRealEntregaBodega",
            "diasLibres",
            "confirmadoNaviera",
            "fechaCas",
            "fechaEntregaContenedorVacio",
            "almacenaje",
            "demorraje",
            "observaciones",
            "fechaRegistroPesos",
        ],
    },
    {
        key: "automatico",
        title: "Automático",
        fields: [
            "tiempoTransitoInternacional",
            "rangoEnvioElectronicoSalida",
            "rangoEtaEnvioElectronico",
            "rangoCarpetas",
            "diasHabilesEtaEnvio",
            "diasHabilesEnvioDesaduanizacion",
            "observacionesCarpetas",
        ],
    },
];


// labels.js
export const labels = {
    prioridad: "Prioridad",
    codigoImportacion: "Código de Importación",
    proveedor: "Proveedor",
    facturaComercial: "Factura Comercial",
    ordenCompra: "Orden de Compra",
    regimen: "Régimen",
    descripcion: "Descripción",
    notificacionBroker: "Notificación Broker",
    referencia: "Orden",

    paisOrigen: "País de Origen",
    paisProcedencia: "País de Procedencia",
    fechaFactura: "Fecha de Factura",
    valorFactura: "Valor de Factura",
    formaPago: "Forma de Pago",
    cantidad: "Cantidad",
    um: "Unidad de Medida",
    entidadEmisoraDcp: "Entidad Emisora DCP",
    numeroPermisoImportacion: "Número Permiso Importación",
    fechaSolicitudRegimen: "Fecha Solicitud Régimen",
    cartaReg21: "Carta REG21",
    fechaSolicitudGarantia: "Fecha Solicitud Garantía",
    aseguradora: "Aseguradora",
    numeroGarantia: "Número de Garantía",
    montoAsegurado: "Monto Asegurado",
    fechaInicioGarantia: "Fecha Inicio Garantía",
    fechaFinGarantia: "Fecha Fin Garantía",
    numeroCdaGarantia: "Número CDA Garantía",
    fechaEnvioPoliza: "Fecha Envío Póliza",
    fechaRecepcionDocumentoOriginal: "Fecha Recepción Documento Original",
    numeroPoliza: "Número Póliza",
    incoterms: "Incoterms",
    fechaRecolectEstimada: "Fecha Recolección Estimada",
    fechaRecolectProveedor: "Fecha Recolección Proveedor",
    fechaRecolectReal: "Fecha Recolección Real",
    fechaReqBodega: "Fecha Req. Bodega",
    fechaMaxReqBodega: "Fecha Máx. Req. Bodega",
    cartaAclaratoria: "Carta Aclaratoria",
    certificadoOrigen: "Certificado de Origen",
    listaEmpaque: "Lista de Empaque",
    cartaGastos: "Carta de Gastos",

    blMaster: "BL Master",
    blHijo: "BL Hijo",
    tipoTransporte: "Tipo de Transporte",
    companiaTransporte: "Compañía de Transporte",
    forwarder: "Forwarder",
    fechaEstEmbarque: "Fecha Estimada Embarque",
    fechaRealEmbarque: "Fecha Real Embarque",
    fechaEstLlegadaPuerto: "Fecha Estimada Llegada Puerto",
    fechaRealLlegadaPuerto: "Fecha Real Llegada Puerto",
    numeroGuia: "Número de Guía",
    fechaRecepcionDocsOriginales: "Fecha Recepción Docs Originales",
    puertoEmbarque: "Puerto de Embarque",

    fechaEnvioElectronico: "Fecha Envío Electrónico",
    fechaPagoLiquidacion: "Fecha Pago Liquidación",
    fechaSalidaAutorizada: "Fecha Salida Autorizada",
    tipoAforo: "Tipo de Aforo",
    refrendo: "Refrendo",
    numeroEntregaEcuapass: "Número Entrega EcuaPass",
    numeroLiquidacion: "Número Liquidación",
    numeroCdaAutorizacion: "Número CDA Autorización",
    numeroCarga: "Número de Carga",
    statusAduana: "Status Aduana",

    fechaFacturacionCostos: "Fecha Facturación Costos",
    numeroContainer: "Número Container",
    cantidadContenedores: "Cantidad de Contenedores",
    peso: "Peso",
    bultos: "Bultos",
    tipoContenedor: "Tipo Contenedor",
    fechaEstDespachoPuerto: "Fecha Estimada Despacho Puerto",
    fechaRealDespachoPuerto: "Fecha Real Despacho Puerto",
    fechaEstEntregaBodega: "Fecha Estimada Entrega Bodega",
    fechaRealEntregaBodega: "Fecha Real Entrega Bodega",
    diasLibres: "Días Libres",
    confirmadoNaviera: "Confirmado Naviera",
    fechaCas: "Fecha CAS",
    fechaEntregaContenedorVacio: "Fecha Entrega Contenedor Vacío",
    almacenaje: "Almacenaje",
    demorraje: "Demorraje",
    observaciones: "Observaciones",
    fechaRegistroPesos: "Fecha Registro Pesos",

    tiempoTransitoInternacional: "Tiempo Tránsito Internacional",
    rangoEnvioElectronicoSalida: "Rango Envío Electrónico Salida",
    rangoEtaEnvioElectronico: "Rango ETA Envío Electrónico",
    rangoCarpetas: "Rango Carpetas",
    diasHabilesEtaEnvio: "Días Hábiles ETA Envío",
    diasHabilesEnvioDesaduanizacion: "Días Hábiles Envío Desaduanización",
    observacionesCarpetas: "Observaciones Carpetas",
};

// catalogFieldMap.js
export const catalogFieldMap = {
    proveedor: "PROVEEDOR",
    paisOrigen: "PAIS_ORIGEN",
    paisProcedencia: "PAIS_ORIGEN",

    formaPago: "FORMAS_PAGO",
    um: "UNIDADES_METRICAS",

    entidadEmisoraDcp: "DCP",
    aseguradora: "ASEGURADORA",

    incoterms: "INCOTERMS",

    tipoTransporte: "TIPO_TRANSPORTE",
    companiaTransporte: "COMPANIA_TRANSPORTE",
    forwarder: "FORWARDER",
    puertoEmbarque: "PUERTO_EMBARQUE",

    tipoAforo: "TIPO_AFORO",
    prioridad: "PRIORIDAD",

    descripcion: "DESCRIPCION",
};

