export const celdasExcel = [
    { header: "CÓDIGO", path: "preembarque.items.codigo" },
    { header: "DESCRIPCIÓN", path: "preembarque.items.descripcion" },
    { header: "QUINTALES SOLICITADOS", path: "preembarque.items.quintalesSolicitados" },
    { header: "N° CAJAS SOLICITADOS", path: "preembarque.items.cajasSolicitados" },
    { header: "QUINTALES DESPACHADOS", path: "preembarque.items.quintalesDespachados" },
    { header: "N° CAJAS DESPACHADOS", path: "preembarque.items.cajasDespachados" },
    { header: "CAUSALES RETRASO", path: "preembarque.items.causalesRetraso" },
    { header: "NOVEDADES DESCARGA", path: "preembarque.items.novedadesDescarga" },
    { header: "ANOMALÍAS TEMPERATURA", path: "preembarque.items.anomaliasTemperatura" },
    { header: "PUERTO DE ARRIBO", path: "preembarque.items.puertoArribo" },
    { header: "MARCA", path: "preembarque.items.marca" },
    { header: "SKU", path: "preembarque.items.sku" },
    { header: "Semana Ingreso Bodega", path: "preembarque.items.semanaIngresoBodega" },
    { header: "YEAR", path: "preembarque.items.year" },
    { header: "SEM SOLICITUD", path: "preembarque.items.semSolicitud" },
    { header: "Delta REQ VS CARGA", path: "preembarque.items.deltaReqVsCarga" },
    { header: "LT HASTA ROUND TRIP WEEK", path: "preembarque.items.ltHastaRoundTripWeek" },
    { header: "MONTH", path: "preembarque.items.month" },
    { header: "SEM REQUERIDA", path: "preembarque.items.semRequerida" },
    { header: "ON TIME", path: "preembarque.items.onTime" },
    { header: "TT TENDER", path: "preembarque.items.ttTender" },
    { header: "Delta Tiempo transito", path: "preembarque.items.deltaTiempoTransito" },
    { header: "SAT UN", path: "preembarque.items.satUN" },
    { header: "SAT CONT", path: "preembarque.items.satCONT" },
    { header: "FLETE PRIMARIO", path: "preembarque.items.fletePrimario" },
    { header: "OTROS", path: "preembarque.items.otros" },
    { header: "SEGURO", path: "preembarque.items.seguro" },
    { header: "SUMA TOTAL", path: "preembarque.items.sumaTotal" },
    { header: "DELTA FECHA SOLICITUD VS ETD", path: "preembarque.items.deltaFechaSolicitudVsETD" },
    { header: "DELTA FECHA SOLICITUD VS CARGA", path: "preembarque.items.deltaFechaSolicitudVsCarga" },
    { header: "LT FECHA CARGA HASTA INGRESO BODEGA ROUND TRIP", path: "preembarque.items.ltFechaCargaHastaIngresoBodega" },
];
