export const celdasExcel = [
    { header: "PROCESO", path: "estado" },
    { header: "CODIGO DE IMPORTACION", path: "inicio.codigoImportacion" },
    { header: "PROVEEDOR", path: "inicio.proveedor" },
    { header: "PRIORIDAD", path: "inicio.prioridad" },
    { header: "PAIS DE ORIGEN", path: "preembarque.paisOrigen" },
    { header: "FACTURA COMERCIAL", path: "inicio.facturaComercial" },
    { header: "FECHA FACTURA", path: "preembarque.fechaFactura" },
    { header: "VALOR FACTURA", path: "preembarque.valorFactura" },
    { header: "N° ORDEN DE COMPRA", path: "inicio.ordenCompra" },
    { header: "FORMA DE PAGO", path: "preembarque.formaPago" },
    { header: "REGIMEN", path: "inicio.regimen" },
    { header: "DESCRIPCION", path: "inicio.descripcion" },
    { header: "CANTIDAD", path: "preembarque.cantidad" },
    { header: "UM", path: "preembarque.um" },
    { header: "STATUS ADUANA", path: "aduana.statusAduana" },
    { header: "ENTIDAD EMISORA DCP", path: "preembarque.entidadEmisoraDcp" },
    { header: "NUMERO DE PERMISO Y/O LICENCIA DE IMPORTACION", path: "preembarque.numeroPermisoImportacion" },
    { header: "FECHA FACTURACIÓN COSTOS IMPORT", path: "despacho.fechaFacturacionCostos" },
    { header: "FECHA DE SOLICITUD DE AUTORIZACION AL REGIMEN", path: "preembarque.fechaSolicitudRegimen" },
    { header: "CARTA REG 21", path: "preembarque.cartaReg21" },
    { header: "FECHA SOLICITUD GARANTÍA", path: "preembarque.fechaSolicitudGarantia" },
    { header: "ASEGURADORA", path: "preembarque.aseguradora" },
    { header: "N.- DE GARANTIA", path: "preembarque.numeroGarantia" },
    { header: "MONTO ASEGURADO", path: "preembarque.montoAsegurado" },
    { header: "FECHA DE INICIO", path: "preembarque.fechaInicioGarantia" },
    { header: "FECHA DE FIN", path: "preembarque.fechaFinGarantia" },
    { header: "NUMERO DE CDA DE GARANTIA 21/72", path: "preembarque.numeroCdaGarantia" },
    { header: "FECHA DE ENVIO GLM POLIZA DE TRANSPORTE", path: "preembarque.fechaEnvioPoliza" },
    { header: "FECHA DE RECEPCION DOCUMENTO ORIGINAL", path: "preembarque.fechaRecepcionDocumentoOriginal" },
    { header: "NUMERO DE POLIZA", path: "preembarque.numeroPoliza" },
    { header: "FECHA DE ENVIO ELECTRONICO", path: "aduana.fechaEnvioElectronico" },
    { header: "FECHA DE PAGO DE LIQUIDACION", path: "aduana.fechaPagoLiquidacion" },
    { header: "FECHA DE SALIDA AUTORIZADA", path: "aduana.fechaSalidaAutorizada" },
    { header: "TIPO DE AFORO", path: "aduana.tipoAforo" },
    { header: "REFRENDO", path: "aduana.refrendo" },
    { header: "NUMERO ENTREGA - ECUAPASS", path: "aduana.numeroEntregaEcuapass" },
    { header: "NUMERO DE LIQUIDACIÓN", path: "aduana.numeroLiquidacion" },
    { header: "NUMERO DE BL MASTER, GUIA O CARTA PORTE", path: "postembarque.blMaster" },
    { header: "NUMERO DE BL HIJO", path: "postembarque.blHijo" },
    { header: "NUMERO DE CONTAINER", path: "despacho.numeroContainer" },
    { header: "PESO", path: "despacho.peso" },
    { header: "BULTOS", path: "despacho.bultos" },
    { header: "TIPO DE TRANSPORTE", path: "postembarque.tipoTransporte" },
    { header: "INCOTERMS", path: "preembarque.incoterms" },
    { header: "COMPAÑIA TRANSPORTE", path: "postembarque.companiaTransporte" },
    { header: "FORWARDER", path: "postembarque.forwarder" },
    { header: "TIPO DE CONTENEDOR", path: "despacho.tipoContenedor" },
    { header: "NOTIFICACION RECIBIDA BROKER", path: "inicio.notificacionBroker" },
    { header: "FECHA DE RECOLECCION ESTIMADA O/C", path: "preembarque.fechaRecolectEstimada" },
    { header: "FECHA DE RECOLECCION DE PROVEEDOR", path: "preembarque.fechaRecolectProveedor" },
    { header: "FECHA DE RECOLECCION REAL", path: "preembarque.fechaRecolectReal" },
    { header: "FECHA ESTIMADA DE EMBARQUE ORIGEN", path: "postembarque.fechaEstEmbarque" },
    { header: "FECHA REAL DE EMBARQUE ORIGEN", path: "postembarque.fechaRealEmbarque" },
    { header: "FECHA ESTIMADA LLEGADA A PUERTO DESTINO", path: "postembarque.fechaEstLlegadaPuerto" },
    { header: "FECHA REAL LLEGADA A PUERTO DESTINO", path: "postembarque.fechaRealLlegadaPuerto" },
    { header: "TIEMPO DE TRANSITO INTERNACIONAL", path: "automatico.tiempoTransitoInternacional" },
    { header: "FECHA ESTIMADA DESPACHO DEL PUERTO", path: "despacho.fechaEstDespachoPuerto" },
    { header: "FECHA REAL DESPACHO DEL PUERTO", path: "despacho.fechaRealDespachoPuerto" },
    { header: "FECHA REQUERIDA EN BODEGA FERRERO", path: "preembarque.fechaReqBodega" },
    { header: "FECHA MAXIMA REQUERIDA EN BODEGA FERRERO", path: "preembarque.fechaMaxReqBodega" },
    { header: "FECHA ESTIMADA DE ENTREGA EN BODEGA", path: "despacho.fechaEstEntregaBodega" },
    { header: "FECHA REAL DE ENTREGA EN BODEGA", path: "despacho.fechaRealEntregaBodega" },
    { header: "DIAS LIBRES", path: "despacho.diasLibres" },
    { header: "CONFIRMADO NAVIERA", path: "despacho.confirmadoNaviera" },
    { header: "FECHA CAS", path: "despacho.fechaCas" },
    { header: "NÚMERO DE GUÍA - DOC TRANSPORTE", path: "postembarque.numeroGuia" },
    { header: "FECHA DE RECEPCIÓN DOCUMENTOS ORIGINALES GLM", path: "postembarque.fechaRecepcionDocsOriginales" },
    { header: "FECHA DE ENTREGA CONTENEDOR VACIO", path: "despacho.fechaEntregaContenedorVacio" },
    { header: "ALMACENAJE", path: "despacho.almacenaje" },
    { header: "DEMORAJE", path: "despacho.demorraje" },
    { header: "RANGO ENVIO ELECTRONICO A SALIDA AUTORIZADA", path: "automatico.rangoEnvioElectronicoSalida" },
    { header: "RANGO ETA A ENVÍO ELECTRÓNICO", path: "automatico.rangoEtaEnvioElectronico" },
    { header: "RANGO CARPETAS", path: "automatico.rangoCarpetas" },
    { header: "N.- CDA DE AUTORIZACIÓN AL RÉGIMEN", path: "aduana.numeroCdaAutorizacion" },
    { header: "PUERTO DE EMBARQUE", path: "postembarque.puertoEmbarque" },
    { header: "ORDEN", path: "inicio.referencia" },
    { header: "NÚMERO DE CARGA", path: "aduana.numeroCarga" },
    { header: "CARTA ACLARATORIA", path: "preembarque.cartaAclaratoria" },
    { header: "CERTIFICADO DE ORÍGEN", path: "preembarque.certificadoOrigen" },
    { header: "LISTA DE EMPAQUE", path: "preembarque.listaEmpaque" },
    { header: "CARTA DE GASTOS", path: "preembarque.cartaGastos" },
    { header: "PAÍS DE PROCEDENCIA", path: "preembarque.paisProcedencia" },
    { header: "FECHA REGISTRO DE PESOS", path: "despacho.fechaRegistroPesos" },
    { header: "DÍAS HÁBILES REAL ETA ENVÍO ELECTRÓNICO", path: "automatico.diasHabilesEtaEnvio" },
    { header: "DÍAS HÁBILES REAL ENVÍO–DESADUANIZACIÓN", path: "automatico.diasHabilesEnvioDesaduanizacion" },
    { header: "OBSERVACIONES", path: "despacho.observaciones" },
    { header: "TIEMPO ETA SALIDA AUTORIZADA DIAS LAB", path: "automatico.diasLabEtaSalidaAutorizada" },
    { header: "FECHA REAL DE LLEGADA - FECHA REAL DESPACHO DEL PUERTO DIAS CALEN", path: "automatico.diasCalLlegadaPuertoDespachoPuerto" },
    { header: "FECHA REAL BOD FERRERO - FECHA REAL LLEGADA PUERTO DIAS CALEN", path: "automatico.diasCalBodegaLlegadaPuerto" },
    { header: "RANGO ENVIO  ELECTRONICO A SALIDA AUTORIZADA", path: "automatico.diasHabilesRealEtaEnvioElectronico" },
];