export const tipoTransporte = [
    "AÉREO",
    "MARÍTIMO",
    "TERRESTRE",
]

export const companiaTransporte = [
    "AGENCIA NAVIERA EXPRESS NETWORK OFFICE EXNETSA S.A.",
    "ATLAS AIR",
    "AVIANCA",
    "BOTERO SOTO",
    "CARGO LUX",
    "CMA-CGM ECUADOR S.A.",
    "COMPAGNIE MARITIME MARFRET",
    "HAPAG LLOYD",
    "IBERIA",
    "KLM",
    "LAN CHILE",
    "LOGITRANS-ACROS SA",
    "MAERSK DEL ECUADOR C.A.",
    "MARGLOBAL S.A.",
    "MSC. ECUADOR C.A.",
    "NA",
    "PACIFIC INTERNATIONAL LINES",
    "SEATRADE ECUADOR",
    "TACA INTERNATIONAL AIRLINES",
    "TRANSOCEANICA COMPAÑIA LIMITADA",
    "UPS",
];

export const forwarder = [
    "ACGROUP WORLDWIDE ECUADOR",
    "AHARTRODT LOGISTICS ECUADOR S.A.",
    "BROOM ECUADOR",
    "CLI SA",
    "DHL EXPRESS",
    "DSV-AIR & SEA S.A.",
    "ECU-WOLRDWIDE",
    "FEDEX",
    "INTERCILSA LOGISTICS",
    "KUEHNE + NAGEL",
    "NA",
    "NAVECUADOR",
    "OPERADORA DEL PACIFICO S.A.",
    "PACIFICLINK",
    "SCHRYVER TRANSPORTES Y LOGISTICA",
    "TOLEPU",
];

export const puertoEmbarque = [
    "ANTWERP",
    "BOLOGNA",
    "BRAMPTON",
    "BRASIL",
    "BUENAVENTURA",
    "BUENOS AIRES",
    "CAMPIÑAS",
    "CARTAGENA",
    "CHICAGO",
    "CINCINATI",
    "CORK",
    "FRANKFURT",
    "GDANSK",
    "GDYNIA",
    "GENOVA",
    "GUARULHOS",
    "IZMIT KORFEZI",
    "KOBE",
    "LA CEJA ANTIOQUIA",
    "LA VIRGINIA",
    "LAZARO",
    "LEIPZIG",
    "LIVORNO",
    "MADRID",
    "MALPENSA",
    "MANZANILLO",
    "MEDELLIN",
    "MEXICO CITY",
    "MILAN",
    "MUMBAI",
    "NAPOLI",
    "NEW YORK",
    "NHAVA SHEVA",
    "PENDIENTE",
    "PUERTO QUETZAL",
    "QUERETARO",
    "RADICATEL",
    "SANTOS",
    "SEATTLE",
    "SEGRATE",
    "TOLUCA",
    "TREVISO-MESTRINO",
    "TRIESTE",
    "VADO LIGURE",
    "VIRACOPOS- CAMPIÑAS",
    "YORK",
    "ZUMPAGO",
];
