export const celdasExcel = [
    { header: "CÓDIGO DE IMPORTACIÓN", path: "inicio.codigoImportacion" },
    { header: "STATUS", path: "aduana.statusAduana" },
    { header: "ORIGEN", path: "preembarque.paisOrigen" },
    { header: "DESTINO", fixedValue: "ECUADOR" },
    { header: "CÓDIGO", path: "preembarque.items.codigo" },
    { header: "DESCRIPCIÓN", path: "preembarque.items.descripcion" },
    { header: "QUINTALES SOLICITADOS", path: "preembarque.items.quintalesSolicitados" },
    { header: "N° CAJAS SOLICITADOS", path: "preembarque.items.cajasSolicitados" },
    { header: "QUINTALES DESPACHADOS", path: "preembarque.items.quintalesDespachados" },
    { header: "N° CAJAS DESPACHADOS", path: "preembarque.items.cajasDespachados" },
    { header: "FORWARDER", path: "postembarque.forwarder" },
    { header: "MOT", path: "postembarque.tipoTransporte" },
    { header: "CONTENEDOR", path: "despacho.numeroContainer" },
    { header: "N° FACTURA", path: "inicio.facturaComercial" },
    { header: "N° ORDEN DE COMPRA", path: "inicio.ordenCompra" },
    { header: "FECHA SOLICITUD", path: "preembarque.fechaSolicitudRegimen" },
    { header: "FECHA DE FACTURA", path: "preembarque.fechaFactura" },
    { header: "WEEKS FACTURACIÓN", path: "automatico.rangoEnvioElectronicoSalida" },
    { header: "ETD", path: "postembarque.fechaEstEmbarque" },
    { header: "WEEK ETD", path: "automatico.rangoEtaEnvioElectronico" },
    { header: "ETA TENTATIVO", path: "postembarque.fechaEstLlegadaPuerto" },
    { header: "ETA REAL", path: "postembarque.fechaRealLlegadaPuerto" },
    { header: "WEEK ETA PUERTO", path: "automatico.rangoCarpetas" },
    { header: "FECHA INGRESO BODEGA", path: "despacho.fechaEstEntregaBodega" },
    { header: "TRANSIT TIME PORT TO PORT", path: "automatico.tiempoTransitoInternacional" },
    { header: "LT HASTA ALMACEN", path: "despacho.diasLibres" },
    { header: "OBSERVACIONES", path: "despacho.observaciones" },
    { header: "CAUSALES RETRASO", path: "preembarque.items.causalesRetraso" },
    { header: "NOVEDADES DESCARGA", path: "preembarque.items.novedadesDescarga" },
    { header: "ANOMALÍAS TEMPERATURA", path: "preembarque.items.anomaliasTemperatura" },
    { header: "PUERTO DE ARRIBO", path: "preembarque.items.puertoArribo" },
    { header: "MARCA", path: "preembarque.items.marca" },
    { header: "SKU", path: "preembarque.items.sku" },
    { header: "Semana Ingreso Bodega", path: "preembarque.items.semanaIngresoBodega" },
    { header: "YEAR", path: "preembarque.items.year" },
    { header: "SEM SOLICITUD", path: "preembarque.items.semSolicitud" },
    { header: "Delta REQ VS CARGA", path: "preembarque.items.deltaReqVsCarga" },
    { header: "DELTA FECHA SOLICITUD VS ETD", path: "preembarque.items.deltaFechaSolicitudVsETD" },
    { header: "DELTA FECHA SOLICITUD VS CARGA", path: "preembarque.items.deltaFechaSolicitudVsCarga" },
    { header: "LT FECHA CARGA HASTA INGRESO BODEGA ROUND TRIP", path: "preembarque.items.ltFechaCargaHastaIngresoBodega" },
    { header: "LT HASTA ROUND TRIP WEEK", path: "preembarque.items.ltHastaRoundTripWeek" },
    { header: "MONTH", path: "preembarque.items.month" },
    { header: "SEM REQUERIDA", path: "preembarque.items.semRequerida" },
    { header: "ON TIME", path: "preembarque.items.onTime" },
    { header: "TT TENDER", path: "preembarque.items.ttTender" },
    { header: "Delta Tiempo transito", path: "preembarque.items.deltaTiempoTransito" },
    { header: "SAT UN", path: "preembarque.items.satUN" },
    { header: "SAT CONT", path: "preembarque.items.satCONT" },
    { header: "FLETE PRIMARIO", path: "preembarque.items.fletePrimario" },
    { header: "OTROS", path: "preembarque.items.otros" },
    { header: "SEGURO", path: "preembarque.items.seguro" },
    { header: "SUMA TOTAL", path: "preembarque.items.sumaTotal" },
    { header: "TIEMPO TRANSITO INTERNACIONAL", path: "automatico.diasCalLlegadaPuertoDespachoPuerto" },
    { header: "DIAS LAB ENVIO ELECTRONICO SALIDA AUTORIZADA", path: "automatico.diasLabEnvioElectronicoSalidaAutorizada" },
    { header: "DIAS LAB ETA SALIDA AUTORIZADA", path: "automatico.diasLabEtaSalidaAutorizada" },
    { header: "DIAS LLEGADA PUERTO - DESPACHO PUERTO", path: "automatico.diasCalLlegadaPuertoDespachoPuerto" },
    { header: "DIAS BODEGA - DESPACHO PUERTO", path: "automatico.diasCalBodegaLlegadaPuerto" },
    { header: "DIAS LAB FACTURACION", path: "automatico.diasLabFacturacion" },
    { header: "RANGO ENVIO ELECTRONICO - SALIDA", path: "automatico.rangoEnvioElectronicoSalida" },
    { header: "RANGO ETA - ENVIO ELECTRONICO", path: "automatico.rangoEtaEnvioElectronico" },
    { header: "RANGO CARPETAS", path: "automatico.rangoCarpetas" },
    { header: "DIAS HAB REAL ETA - ENVIO ELECTRONICO", path: "automatico.diasHabilesRealEtaEnvioElectronico" },
    { header: "DIAS HAB REAL ENVIO - DESADUANIZACION", path: "automatico.diasHabilesRealEnvioDesaduanizacion" },
    { header: "OBSERVACIONES CARPETAS", path: "automatico.observacionesCarpetas" },
    
];
