export const VariableCatalog = {

    META: [
        { key: "proceso", label: "Proceso", path: "proceso", type: "string" },
        { key: "codigoImportacion", label: "Código Importación", path: "codigoImportacion", type: "string" },
        { key: "estado", label: "Estado", path: "estado", type: "string" },
        { key: "anulado", label: "Anulado", path: "anulado", type: "boolean" },
        { key: "currentStage", label: "Etapa Actual", path: "currentStage", type: "string" },
        { key: "createdAt", label: "Fecha Creación", path: "createdAt", type: "date" },
        { key: "updatedAt", label: "Última Actualización", path: "updatedAt", type: "date" },
    ],
    INICIO: [
        { label: "Prioridad", path: "inicio.prioridad", type: "string" },
        { label: "Código Importación (Inicio)", path: "inicio.codigoImportacion", type: "string" },
        { label: "Proveedor", path: "inicio.proveedor", type: "string" },
        { label: "Factura Comercial", path: "inicio.facturaComercial", type: "string" },
        { label: "Orden Compra", path: "inicio.ordenCompra", type: "string" },
        { label: "Régimen", path: "inicio.regimen", type: "string" },
        { label: "Descripción", path: "inicio.descripcion", type: "string" },
        { label: "Notificación Broker", path: "inicio.notificacionBroker", type: "date" },
        { label: "Orden", path: "inicio.referencia", type: "string" },
    ],
    PREEMBARQUE: [
        { label: "País Origen", path: "preembarque.paisOrigen", type: "string" },
        { label: "Fecha Factura", path: "preembarque.fechaFactura", type: "date" },
        { label: "Valor Factura", path: "preembarque.valorFactura", type: "number" },
        { label: "Forma Pago", path: "preembarque.formaPago", type: "string" },
        { label: "Cantidad", path: "preembarque.cantidad", type: "number" },
        { label: "UM", path: "preembarque.um", type: "string" },
        { label: "Entidad Emisora DCP", path: "preembarque.entidadEmisoraDcp", type: "string" },
        { label: "Permiso Importación", path: "preembarque.numeroPermisoImportacion", type: "string" },
        { label: "Fecha Solicitud Régimen", path: "preembarque.fechaSolicitudRegimen", type: "date" },
        { label: "Incoterms", path: "preembarque.incoterms", type: "string" },
        { label: "País Procedencia", path: "preembarque.paisProcedencia", type: "string" },
    ],
    PREEMBARQUE_ITEMS: [
        { label: "Item Código", path: "preembarque.items[].codigo", type: "string" },
        { label: "Item Descripción", path: "preembarque.items[].descripcion", type: "string" },
        { label: "Quintales Solicitados", path: "preembarque.items[].quintalesSolicitados", type: "number" },
        { label: "Cajas Solicitadas", path: "preembarque.items[].cajasSolicitados", type: "number" },
        { label: "Quintales Despachados", path: "preembarque.items[].quintalesDespachados", type: "number" },
        { label: "Cajas Despachados", path: "preembarque.items[].cajasDespachados", type: "number" },
        { label: "Puerto Arribo", path: "preembarque.items[].puertoArribo", type: "string" },
        { label: "Marca", path: "preembarque.items[].marca", type: "string" },
        { label: "SKU", path: "preembarque.items[].sku", type: "string" },
    ],
    POSTEMBARQUE: [
        { label: "BL Master", path: "postembarque.blMaster", type: "string" },
        { label: "BL Hijo", path: "postembarque.blHijo", type: "string" },
        { label: "Tipo Transporte", path: "postembarque.tipoTransporte", type: "string" },
        { label: "Compañía Transporte", path: "postembarque.companiaTransporte", type: "string" },
        { label: "Forwarder", path: "postembarque.forwarder", type: "string" },
        { label: "Fecha Real Embarque", path: "postembarque.fechaRealEmbarque", type: "date" },
        { label: "Fecha Real Llegada Puerto", path: "postembarque.fechaRealLlegadaPuerto", type: "date" },
        { label: "Puerto Embarque", path: "postembarque.puertoEmbarque", type: "string" },
    ],
    ADUANA: [
        { label: "Fecha Envío Electrónico", path: "aduana.fechaEnvioElectronico", type: "date" },
        { label: "Fecha Pago Liquidación", path: "aduana.fechaPagoLiquidacion", type: "date" },
        { label: "Fecha Salida Autorizada", path: "aduana.fechaSalidaAutorizada", type: "date" },
        { label: "Tipo Aforo", path: "aduana.tipoAforo", type: "string" },
        { label: "Refrendo", path: "aduana.refrendo", type: "string" },
        { label: "Número Liquidación", path: "aduana.numeroLiquidacion", type: "string" },
    ],
    DESPACHO: [
        { label: "Fecha Facturación Costos", path: "despacho.fechaFacturacionCostos", type: "date" },
        { label: "Número Contenedor", path: "despacho.numeroContainer", type: "string" },
        { label: "Peso", path: "despacho.peso", type: "number" },
        { label: "Bultos", path: "despacho.bultos", type: "number" },
        { label: "Tipo Contenedor", path: "despacho.tipoContenedor", type: "string" },
        { label: "Fecha Est. Despacho Puerto", path: "despacho.fechaEstDespachoPuerto", type: "date" },
        { label: "Fecha Real Despacho Puerto", path: "despacho.fechaRealDespachoPuerto", type: "date" },
        { label: "Fecha Est. Entrega Bodega", path: "despacho.fechaEstEntregaBodega", type: "date" },
        { label: "Fecha Real Entrega Bodega", path: "despacho.fechaRealEntregaBodega", type: "date" },
        { label: "Días Libres", path: "despacho.diasLibres", type: "number" },
        { label: "Confirmado Naviera", path: "despacho.confirmadoNaviera", type: "number" },
        { label: "Fecha CAS", path: "despacho.fechaCas", type: "date" },
        { label: "Fecha Entrega Contenedor Vacío", path: "despacho.fechaEntregaContenedorVacio", type: "date" },
        { label: "Almacenaje", path: "despacho.almacenaje", type: "number" },
        { label: "Demorraje", path: "despacho.demorraje", type: "number" },
        { label: "Observaciones Despacho", path: "despacho.observaciones", type: "string" },
        { label: "Fecha Registro Pesos", path: "despacho.fechaRegistroPesos", type: "date" },
    ],

    AUTOMATICO: [
        { label: "Proceso", path: "automatico.proceso", type: "string" },
        { label: "Status Aduana", path: "automatico.statusAduana", type: "string" },
        { label: "Tiempo Tránsito Internacional", path: "automatico.tiempoTransitoInternacional", type: "number" },
        { label: "Días Lab Envío Electrónico → Salida Autorizada", path: "automatico.diasLabEnvioElectronicoSalidaAutorizada", type: "number" },
        { label: "Días Lab ETA → Salida Autorizada", path: "automatico.diasLabEtaSalidaAutorizada", type: "number" },
        { label: "Días Cal Llegada Puerto → Despacho Puerto", path: "automatico.diasCalLlegadaPuertoDespachoPuerto", type: "number" },
        { label: "Días Cal Llegada Puerto → Entrega Bodega", path: "automatico.diasCalBodegaLlegadaPuerto", type: "number" },
        { label: "Días Lab Facturación", path: "automatico.diasLabFacturacion", type: "number" },
        { label: "Observaciones Carpetas", path: "automatico.observacionesCarpetas", type: "string" },
        { label: "Rango Envío Electrónico → Salida", path: "automatico.rangoEnvioElectronicoSalida", type: "number" },
        { label: "Rango ETA → Envío Electrónico", path: "automatico.rangoEtaEnvioElectronico", type: "number" },
        { label: "Rango Carpetas", path: "automatico.rangoCarpetas", type: "number" },
        { label: "Días Hábiles Reales ETA → Envío Electrónico", path: "automatico.diasHabilesRealEtaEnvioElectronico", type: "number" },
        { label: "Días Hábiles Reales Envío → Desaduanización", path: "automatico.diasHabilesRealEnvioDesaduanizacion", type: "number" },
    ],

};
